![imagen](./img/ejercicios.png)

In [1]:
import numpy as np

## Ejercicio 1
1. Crea un array que vaya del 0 al 9 y que se llame `my_array`
2. Imprime por pantalla los elementos [9 7 5 3 1] en ese orden.

In [ ]:
my_array = np.arange (10)
print(my_array)
print(my_array[9:0:-2]) # Mejor poner todo el intervalo (::-2)

[0 1 2 3 4 5 6 7 8 9]
[9 7 5 3 1]


## Ejercicio 2
Imprime por pantalla la secuencia [8 7] del array `my_array`

In [ ]:
print(my_array[8:6:-1])

# Otra opcion
print(my_array[-2:-4:-1])

[8 7]
[8 7]


## Ejercicio 3
Imprime por pantalla la secuencia [2 1 0] de `my_array`

In [6]:
print(my_array[2::-1])

# Otra forma
print(np.array(sorted(my_array[:3],reverse = True)))

[2 1 0]
[2 1 0]


## Ejercicio 4
1. Crea una matriz de 4x5, con una secuencia del 1 al 20
2. Invierte totalmente la matriz. Tanto las filas, como las columnas

In [11]:
# 1. Crear matriz
matriz = np.arange(1, 21).reshape(4, 5)
print (matriz)

# 2. Invertir matriz
print(np.flip(matriz))

# Otra forma
print (matriz[::-1, ::-1])

# La traspuesta
print (matriz.T)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
[[20 19 18 17 16]
 [15 14 13 12 11]
 [10  9  8  7  6]
 [ 5  4  3  2  1]]
[[20 19 18 17 16]
 [15 14 13 12 11]
 [10  9  8  7  6]
 [ 5  4  3  2  1]]
[[ 1  6 11 16]
 [ 2  7 12 17]
 [ 3  8 13 18]
 [ 4  9 14 19]
 [ 5 10 15 20]]


## Ejercicio 5

Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[1, 2],
       [6, 7]])
```

In [12]:
# Matriz ejercicio 4
'''
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
'''

# Nueva matriz
new_matriz = matriz[:2, :2]
print (new_matriz)

[[1 2]
 [6 7]]


## Ejercicio 6
Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[ 1,  3,  5],
       [11, 13, 15]])
```

In [ ]:
# Matriz ejercicio 4
'''
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
'''

# Nueva matriz
resultado = matriz[[0, 2], :][:, [0, 2, 4]]
print(resultado)

# Otra forma más sencilla
print (matriz [::2, ::2])

[[ 1  3  5]
 [11 13 15]]
[[ 1  3  5]
 [11 13 15]]


## Ejercicio 7
Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[ 5,  4,  3,  2,  1],
       [10,  9,  8,  7,  6],
       [15, 14, 13, 12, 11]])
```

In [14]:
# Matriz ejercicio 4
'''
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
'''

# Nueva matriz
resultado = matriz[:3, ::-1]
print(resultado)

# Otra forma
print (matriz [:3, ::-1])


[[ 5  4  3  2  1]
 [10  9  8  7  6]
 [15 14 13 12 11]]
[[ 5  4  3  2  1]
 [10  9  8  7  6]
 [15 14 13 12 11]]


## Ejercicio 8
Dado el siguiente array:

```Python
x = np.array(["Loro", "Perro", "Gato", "Loro", "Perro"])
```

Filtra el array para quedarte únicamente con los loros.

Resuélvelo de dos maneras diferentes

In [20]:
x = np.array(["Loro", "Perro", "Gato", "Loro", "Perro"])

# Primera manera
loros = x[x == "Loro"]
print (loros)

# Segunda manera
lugares = np.where(x == "Loro")
loros = x[lugares]
print(loros)

# Otra forma
print (x[x=="Loro"])
print (x[np.where (x=="Loro")])


['Loro' 'Loro']
['Loro' 'Loro']
['Loro' 'Loro']
['Loro' 'Loro']


## Ejercicio 9
Crea una secuencia de 20 elementos y transfórmala en un array compuesto por 2 matrices de 5x2

In [23]:
my_array = np.arange (1,21)
print (my_array)

new_array = my_array.reshape (2,5,2)
print (new_array)

print (my_array.ndim)
print (my_array.shape)
print (my_array.size)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[[[ 1  2]
  [ 3  4]
  [ 5  6]
  [ 7  8]
  [ 9 10]]

 [[11 12]
  [13 14]
  [15 16]
  [17 18]
  [19 20]]]
1
(20,)
20


## Ejercicio 10

Crea un array de 10 0s. ¿Cuánto ocupa en memoria?

Sustituye el 4to elemento por 1, e imprime el array por pantalla

In [25]:
array = np.zeros(10)
print (array)

# Memoria que ocupa
print (array.nbytes)
print (array.itemsize)

# Sustituir el 4to elemento por 1
array[3] = 1
print (array)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
80
8
[0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]


## Ejercicio 11

Crea un vector que vaya del 10 al 49

Inviértelo

In [22]:
# Crear el vector
vector = np.arange (10, 50)
print (vector)

# Invertir el vector
vector_invertido = vector[::-1]
print (vector_invertido)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]
[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


## Ejercicio 12
Encuentra los índices de los valores que no sean 0 del siguiente vector [1,2,0,0,4,0]. El output sería [0, 1, 4]. [Encuentra el método apropiado en la documentación.](https://numpy.org/doc/) Encapsúlalo en una función, con un argumento de entrada de un vector.

In [29]:
# Buscamos los indices que no sean cero
vector = np.array([1, 2, 0, 0, 4, 0])
indices = list(np.nonzero(vector)[0])
print(indices) 

# Otra forma
print (vector[np.where (vector !=0)]) # Si pones * te muestra todo sin corchetes

[np.int64(0), np.int64(1), np.int64(4)]
[1 2 4]


In [ ]:
# Encapsulamos en una función
def indices_no_cero(vector):
    
    return list(np.nonzero(vector)[0])

# Usamos la función
vector = np.array([1, 2, 0, 0, 4, 0])
indices = indices_no_cero(vector)
print(indices)

# Otra forma
def ejer_12 (vector):
    return np.where (vector !=0)[0] # Elegimos el primer elemento con [0]

resultado = ejer_12 (vector)
print (resultado)

[np.int64(0), np.int64(1), np.int64(4)]
[0 1 4]


## Ejercicio 13
Crea una matriz de números aleatorios 10x10. Encuentra los valores mínimo y máximo.

In [ ]:
# Crear una matriz 10x10 con números aleatorios entre 0 y 1
matriz = np.random.rand(10, 10)
matriz_1 = np.random.randint (100, size = (10,10))
print (matriz_1)

# Obtener el valor mínimo y máximo
valor_min = matriz.min()
valor_max = matriz.max()

# Otra forma
valor_min_1 = np.min (matriz)
valor_max_1 = np.max (matriz)


# Mostrar resultados
print(matriz)
print(valor_min)
print(valor_max)
print (valor_min_1)
print (valor_max_1)

[[53 53 31 89  1 10 60 78 61 50]
 [39 75 19 79 66  4 43 51 95 32]
 [71 20 93 47 42 43 37 24 45  7]
 [48 17 43 45 69 69 73 27 99 27]
 [99 75 85 71 33  1  4 38 62  3]
 [20 18 48 63 10 76 73  3 36 10]
 [82 32 69 98 39 98  9 14 82 72]
 [94 58 62 29 10 84 55 62  6 35]
 [11 48 95 19 15 74 95 50 59 99]
 [38  6 48 32 78 81 52 68 25 51]]
[[0.92806591 0.32155054 0.21814661 0.27947387 0.50496902 0.93845362
  0.17008541 0.20802332 0.66705258 0.12582276]
 [0.18442542 0.88872071 0.50617416 0.69890761 0.59658463 0.27376782
  0.25020064 0.22784448 0.82614181 0.08806767]
 [0.97032279 0.89868741 0.62944472 0.54676139 0.805857   0.59904164
  0.13674943 0.07874726 0.47894441 0.45523455]
 [0.34359967 0.020985   0.27113493 0.51240159 0.98698566 0.05909957
  0.64989351 0.36777638 0.21176806 0.10490315]
 [0.44660541 0.43454243 0.4436849  0.05359793 0.68296625 0.15837348
  0.61112567 0.02299801 0.41537722 0.09510081]
 [0.19887875 0.1069331  0.12645914 0.51557012 0.82113645 0.56801927
  0.06609428 0.40385811 0.

## Ejercicio 14
Crea un vector aleatorio de tamaño 30 y calcula su media

In [ ]:
vector = np.random.rand (30)
print (vector)

# Calculamos su media
media = vector.mean()
print (media)


[0.06778561 0.39293661 0.96653613 0.31873184 0.59364541 0.32127952
 0.07614131 0.44218468 0.10566697 0.05358845 0.98841124 0.8624561
 0.71934779 0.15009808 0.27251441 0.07479501 0.58194928 0.49547592
 0.40957695 0.42726806 0.49056572 0.95500969 0.99560223 0.34243511
 0.29779384 0.0549524  0.20475208 0.38665539 0.37065446 0.08969968]
0.41695033223345385


## Ejercicio 15
Crea un array cuadrado de 2D, con las dimensiones que quieras, pero que todo el borde esté compuesto por 1s, y el interior por 0s

In [36]:
# Creamos un array cuadrado de tamaño n x n, con 1s en el borde y 0s en el interior.
def crear_array_borde(n):
    # Crear una matriz llena de ceros
    array = np.zeros((n, n), dtype=int)

    # Poner 1s en el borde
    array[0, :] = 1  # Fila superior
    array[-1, :] = 1  # Fila inferior
    array[:, 0] = 1  # Columna izquierda
    array[:, -1] = 1  # Columna derecha

    return array

# Crear el array con tamaño 5x5
array_borde = crear_array_borde(9)

# Imprimir el array
print(array_borde)

[[1 1 1 1 1 1 1 1 1]
 [1 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 1]
 [1 1 1 1 1 1 1 1 1]]


In [ ]:
# Otra forma


## Ejercicio 16
Crea una matriz de 8x8, y rellénala con 0s y 1s. Tienes que replicar:
```Python
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]
```

In [ ]:
# Crear una matriz 8x8 con el patrón deseado
matriz = np.indices((8, 8)).sum(axis=0) % 2

# Imprimir la matriz
print(matriz)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [49]:
# Otra forma
x= np.zeros ((8,8))

x [::2, 1::2] = 1
x [1::2, ::2] = 1
print (x)

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


## Ejercicio 17
Replica la matriz del apartado anterior, pero en este caso usando [la función `tile`](https://numpy.org/doc/stable/reference/generated/numpy.tile.html)

In [50]:
# Crear una matriz base de 2x2 con el patrón deseado
matriz_base = np.array([[0, 1], [1, 0]])

# Repetir la matriz base para formar una matriz de 8x8
matriz = np.tile(matriz_base, (4, 4))

# Imprimir la matriz
print(matriz)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


## Ejercicio 18
Crea una matriz aleatoria de 5x5 y normaliza sus valores. Para normalizar tienes que restar sus valores por la media(`np.mean`) y dividir el resultado por la desviación estándar(`np.std`).

In [55]:
# Crear una matriz 5x5 con números aleatorios
array = np.random.randint(1,20, (5, 5))

# Calcular la media y la desviación estándar
media = np.mean(array)
desviacion_estandar = np.std(array)

# Normalizar la matriz
array_normalizada = (array - media) / desviacion_estandar

# Mostrar resultados
print(array)
print(array_normalizada)

[[12  7  8 12  8]
 [ 5  1 16 14  9]
 [ 6 17 17  7  8]
 [10 19  2 14  7]
 [ 5 12 14 11  3]]
[[ 0.4672511  -0.5757201  -0.36712586  0.4672511  -0.36712586]
 [-0.99290858 -1.82728554  1.30162805  0.88443957 -0.15853162]
 [-0.78431434  1.51022229  1.51022229 -0.5757201  -0.36712586]
 [ 0.05006262  1.92741077 -1.6186913   0.88443957 -0.5757201 ]
 [-0.99290858  0.4672511   0.88443957  0.25865686 -1.41009706]]


## Ejercicio 19
1. Crea una secuencia de números que vayan del 0 al 10.
2. Crea un nuevo array, que parta del anterior, pero sustituya por el valor -1, todos los elementos cuyo valor se encuentre entre el 3 y el 8.
3. Crea un nuevo array que niegue todos los elementos entre el 3 y el 8

In [61]:
# 1. Creamos una secuencia del 0 al 10
array = np.arange (11)
print (array)

# 2. Creamos un nuevo array, que parta del anterior, pero sustituya por el valor -1, 
# todos los elementos cuyo valor se encuentre entre el 3 y el 8.
array_sustitucion = np.copy(array)  
array_sustitucion[(array >= 3) & (array <= 8)] = -1
print (array_sustitucion)

# 3. Crea un nuevo array que niegue todos los elementos entre el 3 y el 8. 
# NO SE ME OCURRE COMO HACERLO
y = array.copy ()
y [(y>=3) & (y<=8)] *= -1
print (y)

[ 0  1  2  3  4  5  6  7  8  9 10]
[ 0  1  2 -1 -1 -1 -1 -1 -1  9 10]
[ 0  1  2 -3 -4 -5 -6 -7 -8  9 10]
