![imagen](./img/ejercicios.png)

In [3]:
import numpy as np

## Ejercicio 1
1. Crea un array que vaya del 0 al 9 y que se llame `my_array`
2. Imprime por pantalla los elementos [9 7 5 3 1] en ese orden.

In [4]:
my_array = np.arange (10)
print(my_array[9:0:-2])

[9 7 5 3 1]


## Ejercicio 2
Imprime por pantalla la secuencia [8 7] del array `my_array`

In [5]:
print(my_array[8:6:-1])


[8 7]


## Ejercicio 3
Imprime por pantalla la secuencia [2 1 0] de `my_array`

In [6]:
print(my_array[2::-1])

[2 1 0]


## Ejercicio 4
1. Crea una matriz de 4x5, con una secuencia del 1 al 20
2. Invierte totalmente la matriz. Tanto las filas, como las columnas

In [7]:
matriz = np.arange(1, 21).reshape(4, 5)
print (matriz)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


## Ejercicio 5

Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[1, 2],
       [6, 7]])
```

In [8]:
# Matriz ejercicio 4
'''
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
'''

# Nueva matriz
new_matriz = matriz[:2, :2]
print (new_matriz)

[[1 2]
 [6 7]]


## Ejercicio 6
Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[ 1,  3,  5],
       [11, 13, 15]])
```

In [9]:
# Matriz ejercicio 4
'''
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
'''

# Nueva matriz
resultado = matriz[[0, 2], :][:, [0, 2, 4]]
print(resultado)

[[ 1  3  5]
 [11 13 15]]


## Ejercicio 7
Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[ 5,  4,  3,  2,  1],
       [10,  9,  8,  7,  6],
       [15, 14, 13, 12, 11]])
```

In [10]:
# Matriz ejercicio 4
'''
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
'''

# Nueva matriz
resultado = matriz[:3, ::-1]
print(resultado)


[[ 5  4  3  2  1]
 [10  9  8  7  6]
 [15 14 13 12 11]]


## Ejercicio 8
Dado el siguiente array:

```Python
x = np.array(["Loro", "Perro", "Gato", "Loro", "Perro"])
```

Filtra el array para quedarte únicamente con los loros.

Resuélvelo de dos maneras diferentes

In [11]:
x = np.array(["Loro", "Perro", "Gato", "Loro", "Perro"])

# Primera manera
loros = x[x == "Loro"]
print (loros)

# Segunda manera
lugares = np.where(x == "Loro")
loros = x[lugares]
print(loros)

['Loro' 'Loro']
['Loro' 'Loro']


## Ejercicio 9
Crea una secuencia de 20 elementos y transfórmala en un array compuesto por 2 matrices de 5x2

In [12]:
my_array = np.arange (1,21)
print (my_array)

new_array = my_array.reshape (2,5,2)
print (new_array)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[[[ 1  2]
  [ 3  4]
  [ 5  6]
  [ 7  8]
  [ 9 10]]

 [[11 12]
  [13 14]
  [15 16]
  [17 18]
  [19 20]]]


## Ejercicio 10

Crea un array de 10 0s. ¿Cuánto ocupa en memoria?

Sustituye el 4to elemento por 1, e imprime el array por pantalla

In [18]:
array = np.zeros(10)
print (array)

# Memoria que ocupa
array.nbytes

# Sustituir el 4to elemento por 1
array[3] = 1
print (array)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]


## Ejercicio 11

Crea un vector que vaya del 10 al 49

Inviértelo

In [22]:
# Crear el vector
vector = np.arange (10, 50)
print (vector)

# Invertir el vector
vector_invertido = vector[::-1]
print (vector_invertido)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]
[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


## Ejercicio 12
Encuentra los índices de los valores que no sean 0 del siguiente vector [1,2,0,0,4,0]. El output sería [0, 1, 4]. [Encuentra el método apropiado en la documentación.](https://numpy.org/doc/) Encapsúlalo en una función, con un argumento de entrada de un vector.

In [ ]:
# Buscamos los indices que no sean cero
vector = np.array([1, 2, 0, 0, 4, 0])
indices = list(np.nonzero(vector)[0])
print(indices) 

[np.int64(0), np.int64(1), np.int64(4)]


In [26]:
# Encapsulamos en una función
def indices_no_cero(vector):
    
    return list(np.nonzero(vector)[0])

# Usamos la función
vector = np.array([1, 2, 0, 0, 4, 0])
indices = indices_no_cero(vector)
print(indices)

[np.int64(0), np.int64(1), np.int64(4)]


## Ejercicio 13
Crea una matriz de números aleatorios 10x10. Encuentra los valores mínimo y máximo.

In [28]:
# Crear una matriz 10x10 con números aleatorios entre 0 y 1
matriz = np.random.rand(10, 10)

# Obtener el valor mínimo y máximo
valor_min = matriz.min()
valor_max = matriz.max()

# Mostrar resultados
print(matriz)
print(valor_min)
print(valor_max)

[[8.74236686e-01 7.18857642e-01 8.26178749e-01 9.22982469e-01
  7.32529505e-01 2.96211633e-01 8.79328753e-02 7.60494177e-01
  3.87598215e-01 8.55102625e-01]
 [4.18419880e-01 6.97542032e-01 4.14234076e-01 6.41638874e-01
  8.46927577e-01 4.86358241e-01 4.36005493e-02 2.94568132e-01
  8.40426868e-01 8.07170179e-01]
 [4.68346053e-01 1.02680111e-01 6.34647617e-02 2.76623363e-01
  5.16319139e-01 9.00121545e-01 8.05057705e-01 8.91159279e-01
  3.71321563e-01 9.19872524e-01]
 [1.44443364e-01 2.18065778e-01 8.44381219e-01 6.89276347e-01
  2.36552212e-01 5.24231940e-01 6.33219574e-01 6.37617550e-01
  7.96241318e-02 4.48833899e-01]
 [1.92810523e-01 5.37523244e-01 1.06175055e-01 8.41904274e-01
  8.84351574e-01 8.81582445e-01 8.04087275e-01 7.32384669e-01
  2.40792486e-01 3.36282912e-01]
 [2.61167047e-01 7.79357509e-01 2.41643265e-01 6.70465843e-01
  1.41823183e-02 8.12925704e-01 2.51147382e-02 7.83920475e-01
  5.19632012e-01 3.12984280e-01]
 [3.19548298e-01 2.11928567e-01 6.23920732e-01 4.07452987e

## Ejercicio 14
Crea un vector aleatorio de tamaño 30 y calcula su media

In [33]:
vector = np.random.rand (30)
print (vector)

# Calculamos su media
media = vector.mean()
print (media)

[0.88246483 0.86956154 0.94021264 0.83517456 0.26074444 0.18755742
 0.61991358 0.33761257 0.25609607 0.16770786 0.00866566 0.20609332
 0.55300487 0.22208281 0.76725476 0.6001405  0.46719163 0.50226553
 0.63341581 0.25348755 0.19398224 0.77103177 0.07980794 0.50216178
 0.67154952 0.20230202 0.7059194  0.90587241 0.79076466 0.1455825 ]
0.48465407347588785


## Ejercicio 15
Crea un array cuadrado de 2D, con las dimensiones que quieras, pero que todo el borde esté compuesto por 1s, y el interior por 0s

In [36]:
# Creamos un array cuadrado de tamaño n x n, con 1s en el borde y 0s en el interior.
def crear_array_borde(n):
    # Crear una matriz llena de ceros
    array = np.zeros((n, n), dtype=int)

    # Poner 1s en el borde
    array[0, :] = 1  # Fila superior
    array[-1, :] = 1  # Fila inferior
    array[:, 0] = 1  # Columna izquierda
    array[:, -1] = 1  # Columna derecha

    return array

# Crear el array con tamaño 5x5
array_borde = crear_array_borde(9)

# Imprimir el array
print(array_borde)

[[1 1 1 1 1 1 1 1 1]
 [1 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 1]
 [1 1 1 1 1 1 1 1 1]]


## Ejercicio 16
Crea una matriz de 8x8, y rellénala con 0s y 1s. Tienes que replicar:
```Python
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]
```

In [ ]:
# Crear una matriz 8x8 con el patrón deseado
matriz = np.indices((8, 8)).sum(axis=0) % 2

# Imprimir la matriz
print(matriz)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


## Ejercicio 17
Replica la matriz del apartado anterior, pero en este caso usando [la función `tile`](https://numpy.org/doc/stable/reference/generated/numpy.tile.html)

In [ ]:
# Crear una matriz base de 2x2 con el patrón deseado
matriz_base = np.array([[0, 1], [1, 0]])

# Repetir la matriz base para formar una matriz de 8x8
matriz = np.tile(matriz_base, (4, 4))

# Imprimir la matriz
print(matriz)

## Ejercicio 18
Crea una matriz aleatoria de 5x5 y normaliza sus valores. Para normalizar tienes que restar sus valores por la media(`np.mean`) y dividir el resultado por la desviación estándar(`np.std`).

In [41]:
# Crear una matriz 5x5 con números aleatorios
array = np.random.rand(5, 5)

# Calcular la media y la desviación estándar
media = np.mean(array)
desviacion_estandar = np.std(array)

# Normalizar la matriz
array_normalizada = (array - media) / desviacion_estandar

# Mostrar resultados
print(array)
print(array_normalizada)

[[0.1246798  0.34226349 0.40151848 0.45954126 0.92795233]
 [0.13329294 0.87492552 0.54864156 0.76880858 0.9311089 ]
 [0.11351562 0.2424409  0.98037491 0.76982938 0.2164125 ]
 [0.79255851 0.86061504 0.01776891 0.04707861 0.4822672 ]
 [0.62661937 0.07590918 0.2806389  0.79425357 0.71746979]]
[[-1.18436273 -0.49997785 -0.31359801 -0.13109391  1.34224013]
 [-1.15727106  1.17545027  0.149161    0.84167144  1.35216875]
 [-1.21947841 -0.81395853  1.50712941  0.84488228 -0.89582791]
 [ 0.91637417  1.13043829 -1.52063883 -1.42844849 -0.05961204]
 [ 0.39443139 -1.3377652  -0.69381104  0.92170579  0.68019109]]


## Ejercicio 19
1. Crea una secuencia de números que vayan del 0 al 10.
2. Crea un nuevo array, que parta del anterior, pero sustituya por el valor -1, todos los elementos cuyo valor se encuentre entre el 3 y el 8.
3. Crea un nuevo array que niegue todos los elementos entre el 3 y el 8

In [49]:
# 1. Creamos una secuencia del 0 al 10
array = np.arange (11)
print (array)

# 2. Creamos un nuevo array, que parta del anterior, pero sustituya por el valor -1, 
# todos los elementos cuyo valor se encuentre entre el 3 y el 8.
array_sustitucion = np.copy(array)  
array_sustitucion[(array >= 3) & (array <= 8)] = -1
print (array_sustitucion)

# 3. Crea un nuevo array que niegue todos los elementos entre el 3 y el 8. 
# NO SE ME OCURRE COMO HACERLO

[ 0  1  2  3  4  5  6  7  8  9 10]
[ 0  1  2 -1 -1 -1 -1 -1 -1  9 10]
